version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/github-actions:latest
    container_name: github-actions-app
    ports:
      - "8888:8888"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 github-actions-app
    restart: always